### ISSUE TITLE
Cool web games list for contributors to add! (flash, html, java script, etc)

### ISSUE THREAD

**Issue by radmanplays** [3kh0/3kh0-Assets#108]
# 3kh0 (Echo) if your reading this please pin this issue

### this issue will be updated for more games.

Happy wheels (java script version) : https://totaljerkface.com/happy_wheels.tjf
Happy wheels (flash player version) : https://totaljerkface.com/happy_wheels_flash.tjf
Minecraft block  ninja : https://www.newgrounds.com/portal/view/668700
Dungeon craft : https://www.newgrounds.com/portal/view/709231
DoomCraft (dungeon craft but it looks like doom): https://www.newgrounds.com/portal/view/730337
AnimatorVSAnimation(game) : https://shadowgmes.github.io/gfiles/animatorvsanimation/
Match Craft : https://www.newgrounds.com/portal/view/727598
Minecraft Trivia : https://www.newgrounds.com/portal/view/663445
Thirty dollar website : https://thirtydollar.website/
Paper minecraft (scratch) : https://scratch.mit.edu/projects/10128407/ 
Minicraft : https://funhtml5games.com/?play=minicraft
hole.io : https://hole-io.com/
Minecraft cookie clicker (scratch) : https://scratch.mit.edu/projects/13640064/
Appel 3d (scratch): https://scratch.mit.edu/projects/850186748 
Appel (scratch) :  https://scratch.mit.edu/projects/60917032/
Minecraft Appel (scratch): https://scratch.mit.edu/projects/538379594/
Minecraft-ish MMO (scratch, multiplayer) : https://scratch.mit.edu/projects/843162693/
Paper minecraft 1.19 (scratch) : https://scratch.mit.edu/projects/662391280/
Agar.io : https://agar.io/
We Become What We Behold : https://ncase.itch.io/wbwwb
Hobo Simulator : https://fuelvin.itch.io/hobo-simulator
Poom (Doom Pico-8) : https://freds72.itch.io/poom
Grey box testing : https://samhogan.itch.io/grey-box-testing
Pico sonic : https://komehara.itch.io/pico-sonic
Snowball.io : https://snowball-io.io/
Happy glass : https://sites.google.com/view/games-unblockedd/happy-glass
Pacman : https://freepacman.org/
Mortal combat (flash) : https://sites.google.com/view/games-unblockedd/flash-games/mortal-combat
paper.io : https://paper-io.com/
portal 2 (not the flash version) : https://sites.google.com/view/games-unblockedd/portal-2
pou : https://unblockeds-games.com/pou
sansfield : https://lumpytouch.itch.io/bad-monday-simulator
Web-Cleaner : https://db414.itch.io/web-cleaner
Cube Squered : https://spacepro0.itch.io/cube-squared-web-edition
InfraredEscape : https://atmos.uw.edu/~dargan/EarthGamesUW/InfraredEscape/
Murder At Midnight 2 : https://atmos.uw.edu/~dargan/EarthGamesUW/InfraredEscape/
Pig game : https://segs.w3.uvm.edu/ComplianceSeriousGame/
Doodle Warrior : http://personal.denison.edu/~lalla/314s19/zack/index.html
MicroParasites2d : https://www.nms.ac.uk/includes/games/microparasites/index.html
Parkour playground : https://v6p9d9t4.ssl.hwcdn.net/html/3612992/index.html
Comet parkour (its Japanese but at least its a cool game ): https://guriieco.com/webgl/CometParkour/
web GL maze : https://mokinys3.aprc.lt/
MD maze : http://personal.denison.edu/~lalla/314s19/minh/index.html
Pixepal : https://kenney.itch.io/pixepal
Super Mario Maker 2 : https://rudolph-gameplays.itch.io/super-mario-maker-2-lite
Among us single player : https://klopity.itch.io/among-us-single-player-fan-game
gmod 2d : https://andrew22856.itch.io/gmod-2dvery-simple
Territory : https://seconddimension.itch.io/territory
Block steady : https://gustav-k.itch.io/block-steady
Sonic origins pocket edition : https://shafox.itch.io/sonic-origins-pocket-edition
Click the circle : https://vimlark.itch.io/click-the-circle
Minerest : https://wuzzywizard.itch.io/minerest
[BigShot]Rune : https://sierpinski-simon.itch.io/bigshotrune
Useless box simulator : https://lemonadode.itch.io/ubs
Hook job : https://jinglejosh.itch.io/hook-job
gta 6 (goat theft auto 6) : https://p9rayo.itch.io/gta6-mobile
geometry dash 2 (wait dont actu-): https://michipro9470yt.itch.io/geometry-dash-2
One jump : https://a5h.itch.io/one-jump
Wolfenstein 2d : https://mrcutecat.itch.io/wolfenstein-2d
Subprime Delivery : https://recrafted-studios.itch.io/subprime-delivery
Windows XP Simulator : https://alexandrechups.itch.io/windows-xp-simulator
Mess Desktop 98 : https://meta-fool.itch.io/messy-desktop-98
Beepbox : https://www.beepbox.co/
Modbox (beep box mod) : https://moddedbeepbox.github.io/3.0
Jummbox (another beep box mod) : https://jummbus.bitbucket.io/
Pandorasbox (another another beep box mod): https://paandorasbox.github.io/
blubox (another another another beep box mod) : https://bluaxolotlbox.neocities.org/
sandbox (another another another another beep box mod) : https://parad0xstuff.github.io/sandbox-2.0
Cardboardbox (another another another another another beep box Mod) : https://hidden-realm.github.io/cardboardbox
Synthbox (another another another another another another beep mod) : https://synthbox.co/
Peet a lock : https://play.famobi.com/peet-a-lock/A1000-10
Emoji flow : https://play.famobi.com/emoji-flow/A1000-10
Curve ball : https://play.famobi.com/curve-ball-3d/A1000-10

**Comment by Rahib777-7** [comment]
we arent adding all of that i told you 
also wrong place 
[3kh0/website-v4](http://github.com/3kh0/website-v4)

**Comment by Rahib777-7** [comment]
no

**Comment by Russell2259** [comment]
@radmanplays Please do not spam issues.
