### ISSUE TITLE
add ads to the games with an anti adblock

### ISSUE THREAD

**Issue by Rahib777-7** [3kh0/3kh0-Assets#54]
the games need ads so 3kh0 makes 10,000$ more

**Comment by SipSup3314** [comment]
bro friggin no please dont

**Comment by Rahib777-7** [comment]
> bro friggin no please dont

but astra wanted 3kh0 to earn money

**Comment by aeiea** [comment]
rahib no u already broke the main site for me

**Comment by Rahib777-7** [comment]
> rahib no u already broke the main site for me

dont use adblock then

**Comment by 3kh0** [comment]
not happening
