### ISSUE TITLE
How to play 3kh0

### ISSUE THREAD

**Issue by Rahib777-7** [3kh0/3kh0-Assets#63]
# How to access 3kh0
We are well aware that the main 3kh0 repo is down. But we still have a couple of links you can use.

https://3kh0.net (Offical)
https://3v3ry0n3.github.io/3kh0-Backup-v4 (backup)

You can check the status at https://status.3kh0.net to see the status of official mirrors and other instances

Join the discord for more links.

**Comment by 3kh0** [comment]
New status page btw

https://status.3kh0.net/status/3kh0

**Comment by Rahib777-7** [comment]
> New status page btw
> 
> https://status.3kh0.net/status/3kh0

how do you add working mirrors to there?

**Comment by Rahib777-7** [comment]
because i have a lot more
