### ISSUE TITLE
Add Rhythm Plus

### ISSUE THREAD

**Issue by JMcrafter26** [3kh0/3kh0-Assets#70]
I found a nice game and I think it would fit perfect with the other games.
It's called: [rhythm-plus](https://rhythm-plus.com) and it is even public on github: 
https://github.com/henryzt/Rhythm-Plus-Music-Game

Thank you

**Comment by WolfKing569624** [comment]
Can you add kart wars

**Comment by Russell2259** [comment]
@WolfKing569624 Please open a new issue if you want that game added.
