### ISSUE TITLE
Add Backyard Baseball

### ISSUE THREAD

**Issue by Minemaster121** [3kh0/3kh0-Assets#75]
Could you add backyard baseball (NOT the flash edition) A link to the game is:
https://kbhgames.com/game/backyard-baseball

**Comment by aeiea** [comment]
sorry, but that's a PC game.
You can only play web games, E.G. HTML5 games, built unity games(devs have to specifically build for this option), or flash games.
backyard baseball is running on an emulator(requires a server) so we cant add it.

- @aeiea, 3kh0 dev
