### ISSUE TITLE
Major hold up

### ISSUE THREAD

**Issue by frigidus5** [3kh0/3kh0-Assets#77]
ok major hold up, i keep getting fake pop up’s that lead me to adult websites on 3kh0.net.
are you aware of this??
![1E3ECECC-5E2D-477A-8CFE-3EA3CBAA8B0F](https://user-images.githubusercontent.com/129239408/234152639-34a4c064-9606-45d5-9323-9edb4d69b9c8.jpeg)

**Comment by aeiea** [comment]
ads

**Comment by aeiea** [comment]
chaturbate💀💀💀💀💀💀💀💀💀

**Comment by frigidus5** [comment]
you contribute to this, can you remove it? pls

**Comment by aeiea** [comment]
sorry but the repo for the website was taken down, this repo just contains the games used in 3kh0. i used to have write access but now 3kh0.net, 3kh0.github.io and other stuff is forever gone until the github devs restore the repo

tl;dr:
code for site taken down, can no longer change the site.

**Comment by aeiea** [comment]
also:
flask is cool, nice

**Comment by frigidus5** [comment]
thanks
