### ISSUE TITLE
PLEASE NOTICE!!!!

### ISSUE THREAD

**Issue by frigidus5** [3kh0/3kh0-Assets#82]
thanks for making a good project. have 3 months of free spotify premium!!
code: Z9PAkms2tW

**Comment by aeiea** [comment]
micrseft rawerds

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/236349578-87c4f5bf-f652-4b47-92e7-fed82c7f7ad4.png)


thanks king

**Comment by frigidus5** [comment]
welcome bro, you saved me so much time tho by copying those games like sheesh
