### ISSUE TITLE
Cookie clicker name

### ISSUE THREAD

**Issue by Crimson7973** [3kh0/3kh0-Assets#83]
Add the ability to set your bakerys name is cookie clicker as having your name as "generatecoookies" or "(yournamehere)saysopensesame allows you to access the debug panel

**Comment by frigidus5** [comment]
basically a way of saying “allow the ability to hack” 💀💀💀

**Comment by Crimson7973** [comment]
Yes lol

**Comment by frigidus5** [comment]
i don’t really think he’s gonna add that but if he does lol

**Comment by aeiea** [comment]
you need a space to activate the hack 💀
so instead of `(yournamehere)saysopensesame` do `(yournamehere) saysopensesame`
