### ISSUE TITLE
Add rhythm-plus game

### ISSUE THREAD

**Issue by JMcrafter26** [3kh0/3kh0-Assets#84]
I found a nice game and I think it would fit perfect with the other games.
It's called: [rhythm-plus](https://rhythm-plus.com/) and it is even public on github:
https://github.com/henryzt/Rhythm-Plus-Music-Game

Thank you

**Comment by Russell2259** [comment]
Please do not open multiple of the same issue.

**Comment by JM26-NET** [comment]
Didn’t you say to me to open another issue?
