### ISSUE TITLE
sorry i keep reporting issues to ask questions but this is a major hold up

### ISSUE THREAD

**Issue by frigidus5** [3kh0/3kh0-Assets#85]
i looked at your profile, it seems to be you cause of the adsense stuff but major hold up because you make an unblocked games website and telling google to take em down??? the question i ask too tho
![google report](https://user-images.githubusercontent.com/129239408/236698750-ec8491a7-276a-4db6-95c9-bf3ece6be5a2.png)

**Comment by Russell2259** [comment]
This issue is not relevant to this repository. If this is an issue please contact 3kh0 directly.
