### ISSUE TITLE
Add Monkey Kart

### ISSUE THREAD

**Issue by NotJack173** [3kh0/3kh0-Assets#86]
My friends have been wanting too play it since its blocked could you add it?
we have tried to get it but dont know enough please help

**Comment by Russell2259** [comment]
For this issue to be valid please provide a url. Please keep in mind that we cannot add desktop games, mobile games or multiplayer games.

**Comment by NotJack173** [comment]
Monkey mart is a web game that ive seen its on geometry spot that has been blocked

**Comment by Russell2259** [comment]
We need a url to add it. If you cannot provide that this isue will be closed. I recommend finding the url on a home device.

**Comment by Russell2259** [comment]
You requested a game called monkey kart not monkey mart.

**Comment by NotJack173** [comment]
sorry XD i guess auto correct?
im sorry for the misunderstanding

**Comment by Russell2259** [comment]
Oops, looks like I misread when I changed the title. I'm going to close this issue because the game already exists.
