### ISSUE TITLE
Not a issue just a idea

### ISSUE THREAD

**Issue by NotJack173** [3kh0/3kh0-Assets#87]
Why not use ruffle to run flash games?
like
binding of isaac
mario 64
and more?
it would open up a whole bunch of games!

**Comment by Russell2259** [comment]
Ruffle is not incredibly compatible, so it has not been used for many games. If you would like any specific game, please open an issue for it to be added or open a pull request with the game assets.

**Comment by aeiea** [comment]
> mario 64 = flash game


im pretty sure mario isnt a flash game, and that it's already added
