### ISSUE TITLE
Add Binding of Isaac

### ISSUE THREAD

**Issue by NotJack173** [3kh0/3kh0-Assets#89]
Thank you for replying Russell2259
i am interested in binding of isaac being added
Thanks!

**Comment by Russell2259** [comment]
@NotJack173 As I said before please include a link to the game. This issue will be closed if one is not provided.

**Comment by NotJack173** [comment]
https://kbhgames.com/game/binding-of-isaac

**Comment by aeiea** [comment]
same thing as
https://github.com/3kh0/3kh0-Assets/issues/75#issuecomment-1532268039

**Comment by NotJack173** [comment]
No its not
im looking for the flash version but
nevermind i ended up using the swf file
no thanks to yall :(

**Comment by aeiea** [comment]
oh sry i thought you meant the actual game(on steam)

**Comment by NotJack173** [comment]
no its fine 
i have gotten the game and am now using it on my own website

**Comment by Rahib777-7** [comment]
added
