### ISSUE TITLE
Doom

### ISSUE THREAD

**Issue by NotJack173** [3kh0/3kh0-Assets#90]
Doom is responding with 404: not found
could yall explain why its not loading the data?

**Comment by Russell2259** [comment]
Could you please send a screenshot so we can further investigate the issue?

**Comment by NotJack173** [comment]
When i go to the doom site to use it sends me 
![image](https://github.com/3kh0/3kh0-Assets/assets/127347011/d5b026c9-966a-448a-ae05-1bf30954db64)

**Comment by Russell2259** [comment]
It looks like you have the wrong url. Try replacing the doom path with the actual doom folder (you can find it the repo).
