### ISSUE TITLE
Githack is blocked

### ISSUE THREAD

**Issue by byronbytes** [3kh0/3kh0-Assets#91]
![image](https://github.com/3kh0/3kh0-Assets/assets/53088136/961861f2-f7e4-4db7-af1c-3549bf102387)
Unable to add any of these since on chromebook they are blocked, and embedding it to an iframe would cause the same issue.

Also shockingly your main 3kh0 page was also blocked but I didn't know where to put this
![Screenshot 2023-05-11 8 34 06 AM](https://github.com/3kh0/3kh0-Assets/assets/53088136/50f7354d-e985-4559-acd3-7d598d918d98)

**Comment by Russell2259** [comment]
You can use my repo https://github.com/Russell2259/3kh0-CDN to proxy the games.

**Comment by Russell2259** [comment]
I would not recommend replit for hosting. You can easily deploy it to any other server using the buttons in the repo's readme.

**Comment by byronbytes** [comment]
I tried heroku and got this
![image](https://github.com/3kh0/3kh0-Assets/assets/53088136/94bb9928-a7fc-4d41-8a4b-bb13d2f99264)

**Comment by Russell2259** [comment]
Try using render...

**Comment by byronbytes** [comment]
![image](https://github.com/3kh0/3kh0-Assets/assets/53088136/a3ff2910-5a77-431f-8c89-ff94fa85f142)
🤷

**Comment by Rahib777-7** [comment]
(it supports replit)
