### ISSUE TITLE
please add this game.

### ISSUE THREAD

**Issue by radmanplays** [3kh0/3kh0-Assets#94]
please add these game to the website :

Minecraft Tower Defense : https://www.newgrounds.com/portal/view/585245/format/flash?emulate=flash
Minecraft Tower Defense 2 : https://www.newgrounds.com/portal/view/593976/format/flash?emulate=flash

**Comment by aeiea** [comment]
adding

**Comment by NotJack173** [comment]
i have the code/link already XD pretty easy for me to add flash games

**Comment by radmanplays** [comment]
> i have the code/link already XD pretty easy for me to add flash games
i made a pull request of my own game request in issues XD

**Comment by aeiea** [comment]
k

<details>
  <summary>totally not promoting a friend's projects</summary>
  you should check out https://github.com/host008/flashtools
  it makes adding <strong>flash</strong> games to 3kh0 so much easier
</details>

**Comment by Rahib777-7** [comment]
added
